main: me.warpednova.guibanner.Main
version: 2.3
name: GUIBanner
description: A customizeable, user-friendly interface for tempbanning players!
api-version: 1.12
author: WarpedNova
depends: ["Essentials"]

commands:
    tempban:
      usage: /tempban <Player_Name>
      description: Tempbans a player!
    guireload:
      usage: /guireload
      description: Reloads the configuration file!
